### ISSUE TITLE
Todo before release

### ISSUE THREAD

**Issue by phiilu** [phiilu/mailman#9]
## Frontend

- [x] Add CRUD functionality for domains, accounts, aliases, tls policies

- [x] Authentication for admin users and non admin users

- [x] Validation for all forms

- [x] Improve data representation

## Docs

- [x] Add Readme

- [x] Write documentation: How to deploy mailman
